namespace Application.DTO.Admin
{
    public class CreateApplicationDto
    {
        public string Name { get; set; }
        // AppId and AppKey will be generated by the system, but can be provided for specific cases
        public string? AppId { get; set; }
        public string? AppKey { get; set; }
    }
}
